name = "work-out"
compatibility_date = "2024-12-01"
pages_build_output_dir = "frontend/dist"

[[d1_databases]]
binding = "DB"
database_name = "work-out"
database_id = "1f508808-7ba5-4b72-a1a2-190b69d2959d"
